### ISSUE TITLE
i got a type error "download() got an unexpected keyword argument 'fuzzy' "

### ISSUE THREAD

**Issue by shbaek916** [ZPdesu/Barbershop#17]
i was trying your model and entered the code below

!python main.py --im_path1 90.png --im_path2 15.png --im_path3 117.png --sign realistic --smooth 5

Then I got this 'fuzzy' argument error.

Downloading StyleGAN2 checkpoint: pretrained_models/ffhq.pt
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    main(args)
  File "main.py", line 18, in main
    ii2s = Embedding(args)
  File "/content/drive/My Drive/StyleGAN_dir/Barbershop/models/Embedding.py", line 23, in __init__
    self.net = Net(self.opts)
  File "/content/drive/My Drive/StyleGAN_dir/Barbershop/models/Net.py", line 15, in __init__
    self.load_weights()
  File "/content/drive/My Drive/StyleGAN_dir/Barbershop/models/Net.py", line 22, in load_weights
    download_weight(self.opts.ckpt)
  File "/content/drive/My Drive/StyleGAN_dir/Barbershop/utils/model_utils.py", line 17, in download_weight
    output=weight_path, fuzzy=True)
TypeError: download() got an unexpected keyword argument 'fuzzy'

I couldn't find this 'fuzzy' argument you used in gdown.download method.
Can you tell me what this is?

**Comment by shbaek916** [comment]
I was using google colab and just solved the problem
!pip install gdown==4.2.0 

or use the right version, find it on this repo, under environment.

**Comment by qo4on** [comment]
How did you run this in Colab? I have an error:
```
!conda env update -f environment/environment.yml -n Barbershop

Ran pip subprocess with arguments:
['/usr/local/envs/Barbershop/bin/python', '-m', 'pip', 'install', '-U', '-r', '/content/Barbershop/environment/condaenv.cikg8f4g.requirements.txt']
Pip subprocess output:
Collecting beautifulsoup4==4.10.0
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting cachetools==4.2.4
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting charset-normalizer==2.0.7
  Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting click==8.0.3
  Downloading click-8.0.3-py3-none-any.whl (97 kB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0


CondaEnvException: Pip failed
```

**Comment by shbaek916** [comment]
sorry, I don't know how to solve that problem

**Comment by ZPdesu** [comment]
> How did you run this in Colab? I have an error:
> 
> ```
> !conda env update -f environment/environment.yml -n Barbershop
> 
> Ran pip subprocess with arguments:
> ['/usr/local/envs/Barbershop/bin/python', '-m', 'pip', 'install', '-U', '-r', '/content/Barbershop/environment/condaenv.cikg8f4g.requirements.txt']
> Pip subprocess output:
> Collecting beautifulsoup4==4.10.0
>   Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
> Collecting cachetools==4.2.4
>   Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
> Collecting charset-normalizer==2.0.7
>   Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
> Collecting click==8.0.3
>   Downloading click-8.0.3-py3-none-any.whl (97 kB)
> 
> Pip subprocess error:
> ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
> ERROR: No matching distribution found for clip==1.0
> 
> 
> CondaEnvException: Pip failed
> ```

Please refer to https://github.com/ZPdesu/Barbershop/issues/18#issue-1095200457
