### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by Daniel-Ri** [ZPdesu/Barbershop#20]
I tried to run the `main.py` by following the steps in ReadMe and got this error. What should I do to fix this?
## Steps to Reproduce
```
$ python main.py --im_path1 90.png --im_path2 15.png --im_path3 117.png --sign realistic --smooth 5
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from models.Embedding import Embedding
  File "/home/danielr/Barbershop/models/Embedding.py", line 3, in <module>
    from models.Net import Net
  File "/home/danielr/Barbershop/models/Net.py", line 3, in <module>
    from models.stylegan2.model import Generator
  File "/home/danielr/Barbershop/models/stylegan2/model.py", line 11, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/danielr/Barbershop/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/danielr/Barbershop/models/stylegan2/op/fused_act.py", line 14, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/danielr/anaconda3/envs/Barbershop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "/home/danielr/anaconda3/envs/Barbershop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1202, in _jit_compile
    with_cuda=with_cuda)
  File "/home/danielr/anaconda3/envs/Barbershop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1279, in _write_ninja_file_and_build_library
    verbose)
  File "/home/danielr/anaconda3/envs/Barbershop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1369, in _prepare_ldflags
    extra_ldflags.append('-L{}'.format(_join_cuda_home('lib64')))
  File "/home/danielr/anaconda3/envs/Barbershop/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1827, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

## Expected Behavior
It should produce the image results.

## Environment Information
<details>
<summary>`conda info`</summary>

```
$ conda info

     active environment : Barbershop
    active env location : /home/danielr/anaconda3/envs/Barbershop
            shell level : 2
       user config file : /home/danielr/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.5=0
                          __linux=5.11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/danielr/anaconda3  (writable)
      conda av data dir : /home/danielr/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/danielr/anaconda3/pkgs
                          /home/danielr/.conda/pkgs
       envs directories : /home/danielr/anaconda3/envs
                          /home/danielr/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Linux/5.11.0-43-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

<details>
<summary>`conda config --show-sources` </summary>

```
$ conda config --show-sources 
# no output
```
</details>

<details> 
<summary> `conda list --show-channel-urls` </summary>

```
$ conda list --show-channel-urls 
# packages in environment at /home/danielr/anaconda3/envs/Barbershop:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
argcomplete               1.12.3             pyhd3eb1b0_0    defaults
argon2-cffi               20.1.0           py37h27cfd23_1    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
beautifulsoup4            4.10.0                   pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2021.10.26           h06a4308_2    defaults
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8        py37h06a4308_0    defaults
cffi                      1.14.6           py37h400218f_0    defaults
charset-normalizer        2.0.7                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
cloudpickle               1.6.0                      py_0    defaults
cudatoolkit               11.0.221             h6bb024c_0    defaults
cycler                    0.10.0                   py37_0    defaults
cytoolz                   0.11.0           py37h7b6447c_0    defaults
dask-core                 2021.8.0           pyhd3eb1b0_0    defaults
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.4.1            py37h295c915_0    defaults
decorator                 5.0.9              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
deprecated                1.2.13                   pypi_0    pypi
dlib                      19.22.1                  pypi_0    pypi
entrypoints               0.3                      py37_0    defaults
et-xmlfile                1.1.0                    pypi_0    pypi
expat                     2.4.1                h2531618_2    defaults
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.4.0                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0    defaults
freetype                  2.10.4               h5ab3b9f_0    defaults
fsspec                    2021.7.0           pyhd3eb1b0_0    defaults
ftfy                      6.0.3                    pypi_0    pypi
gdown                     4.2.0                    pypi_0    pypi
glib                      2.69.1               h5202010_0    defaults
gmp                       6.2.1                h2531618_2    defaults
gnutls                    3.6.15               he1e5248_0    defaults
google-api-core           1.31.4                   pypi_0    pypi
google-api-python-client  2.7.0                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
googleapis-common-protos  1.54.0                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
httplib2                  0.19.1                   pypi_0    pypi
huggingface-hub           0.1.2                    pypi_0    pypi
icu                       58.2                 he6710b0_3    defaults
idna                      3.3                      pypi_0    pypi
imageio                   2.9.0              pyhd3eb1b0_0    defaults
importlib-metadata        3.10.0           py37h06a4308_0    defaults
importlib_metadata        3.10.0               hd3eb1b0_0    defaults
intel-openmp              2021.3.0          h06a4308_3350    defaults
ipykernel                 6.2.0            py37h06a4308_1    defaults
ipython                   7.26.0           py37hb070fc8_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.3              pyhd3eb1b0_1    defaults
jedi                      0.18.0           py37h06a4308_1    defaults
jinja2                    3.0.1              pyhd3eb1b0_0    defaults
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                      py_2    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            6.1.12             pyhd3eb1b0_0    defaults
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyter_core              4.7.1            py37h06a4308_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
kiwisolver                1.3.1            py37h2531618_0    defaults
lame                      3.100                h7b6447c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15                 h63c8f33_5    defaults
libidn2                   2.3.2                h7f8727e_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtasn1                  4.16.0               h27cfd23_0    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libuv                     1.40.0               h7b6447c_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.10               hb55368b_3    defaults
locket                    0.2.1            py37h06a4308_1    defaults
lz4-c                     1.9.3                h295c915_1    defaults
markupsafe                2.0.1            py37h27cfd23_0    defaults
matplotlib-base           3.3.4            py37h62a2d02_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mistune                   0.8.4           py37h14c3975_1001    defaults
mkl                       2021.3.0           h06a4308_520    defaults
mkl-service               2.4.0            py37h7f8727e_0    defaults
mkl_fft                   1.3.0            py37h42c9631_2    defaults
mkl_random                1.2.2            py37h51133e4_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py37h06a4308_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  2.6.2              pyhd3eb1b0_0    defaults
ninja                     1.10.2               hff7bd54_1    defaults
notebook                  6.4.3            py37h06a4308_0    defaults
numpy                     1.20.3           py37hf144106_0    defaults
numpy-base                1.20.3           py37h74d4b33_0    defaults
oauth2client              4.1.3                    pypi_0    pypi
olefile                   0.46                       py_0    defaults
opencv-python             4.5.4.58                 pypi_0    pypi
openh264                  2.1.0                hd408876_0    defaults
openjpeg                  2.3.0                h05c96fa_1    defaults
openpyxl                  3.0.7                    pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0    defaults
packaging                 21.0               pyhd3eb1b0_0    defaults
pandocfilters             1.4.3            py37h06a4308_1    defaults
parso                     0.8.2              pyhd3eb1b0_0    defaults
partd                     1.2.0              pyhd3eb1b0_0    defaults
pcre                      8.45                 h295c915_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.3.1            py37h2c7a002_0    defaults
pip                       21.2.2           py37h06a4308_0    defaults
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.17             pyh06a4308_0    defaults
prompt_toolkit            3.0.17               hd3eb1b0_0    defaults
protobuf                  3.19.1                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyqt5                     5.13.0                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyrsistent                0.17.3           py37h7b6447c_0    defaults
pysocks                   1.7.1                    pypi_0    pypi
python                    3.7.11               h12debd9_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-magic              0.4.24                   pypi_0    pypi
pytorch                   1.7.1           py3.7_cuda11.0.221_cudnn8.0.5_0    pytorch
pytorch-fid               0.2.1                    pypi_0    pypi
pytorch-msssim            0.2.1                    pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.1.1            py37h7b6447c_2    defaults
pyyaml                    5.4.1            py37h27cfd23_1    defaults
pyzmq                     22.2.1           py37h295c915_1    defaults
qdarkgraystyle            1.0.2                    pypi_0    pypi
qdarkstyle                3.0.2                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 5.1.0              pyhd3eb1b0_0    defaults
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
readline                  8.1                  h27cfd23_0    defaults
regex                     2021.11.2                pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
sacremoses                0.0.46                   pypi_0    pypi
scikit-image              0.18.1           py37ha9443f7_0    defaults
scikit-learn              1.0.1                    pypi_0    pypi
scipy                     1.6.2            py37had2a1c9_1    defaults
send2trash                1.5.0              pyhd3eb1b0_1    defaults
setuptools                52.0.0           py37h06a4308_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
soupsieve                 2.3.1                    pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0    defaults
terminado                 0.9.4            py37h06a4308_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
threadpoolctl             3.0.0                    pypi_0    pypi
tifffile                  2020.10.1        py37hdd07704_2    defaults
tk                        8.6.10               hbc83047_0    defaults
tokenizers                0.10.3                   pypi_0    pypi
toolz                     0.11.1             pyhd3eb1b0_0    defaults
torchaudio                0.7.2                      py37    pytorch
torchdiffeq               0.2.2                    pypi_0    pypi
torchvision               0.8.2                py37_cu110    pytorch
tornado                   6.1              py37h27cfd23_0    defaults
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
transformers              4.12.3                   pypi_0    pypi
typing_extensions         3.10.0.0           pyh06a4308_0    defaults
uritemplate               3.0.1                    pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.37.0             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
wrapt                     1.13.3                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zeromq                    4.3.4                h2531618_0    defaults
zipp                      3.5.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.9                haebb681_0    defaults
```
</details>

**Comment by Daniel-Ri** [comment]
Thank you for the response @gordinmitya. But I have already installed `cudatoolkit` through `conda`.
When I tried to run `torch.cuda.is_available()`, I got `True`.

What mistep did I do?

**Comment by myuanz** [comment]
`torch.utils.cpp_extension` needs `CUDA_HOME`, Generally it's `/opt/cuda`

**Comment by MarkZXZX** [comment]
I meet same problem when I use ubuntu inside Win11, then I find nvcc can not work in ubuntu. When I fix nvcc, it works!
Maye it's useful.

**Comment by jaanonim** [comment]
I have the same problem.

**Comment by jaanonim** [comment]
@MarkZXZX how did you fix nvcc on wsl2?

**Comment by Bonnie-gift** [comment]
hi have you ever solved
