### ISSUE TITLE
OSError: /apply/anaconda3/envs/Barber_shop/lib/python3.7/site-packages/torch/lib/../../../../libcublas.so.11: undefined symbol: free_gemm_select, version libcublasLt.so.11

### ISSUE THREAD

**Issue by 805094591** [ZPdesu/Barbershop#22]
python main.py --im_path1 1.png --im_path2 2.png --im_path3 3.png --sign realistic --smooth 7
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import torch
  File "/apply/anaconda3/envs/Barber_shop/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/apply/anaconda3/envs/Barber_shop/lib/python3.7/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/apply/anaconda3/envs/Barber_shop/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /apply/anaconda3/envs/Barber_shop/lib/python3.7/site-packages/torch/lib/../../../../libcublas.so.11: undefined symbol: free_gemm_select, version libcublasLt.so.11

**Comment by 805094591** [comment]
That phenomenon disappeared and the project ran well by reinstalling the system～Thank you～
