### ISSUE TITLE
CUDA Out Of Memory

### ISSUE THREAD

**Issue by Hamza4040** [ZPdesu/Barbershop#37]
Hello,
I need your help. I have researched and notice the solution of this error is "**to reduce batch size**", but I am unable to find the batch size.
can you please tell me where is batch_size defined? so that i can reduce to overcome this error.
Thanks and Cheers

![image](https://user-images.githubusercontent.com/49815904/165355119-199c254c-6923-4499-b81c-75ba55a4e58e.png)

**Comment by Styml** [comment]
same problem here

```(env1) stym@stym:~/Documents/GitHub/Barbershop$ python main.py --im_path1 my1.png --im_path2 my2.png --sign realistic --smooth 1
Loading StyleGAN2 from checkpoint: pretrained_models/ffhq.pt
Setting up Perceptual loss...
Loading model from: /home/stym/Documents/GitHub/Barbershop/losses/lpips/weights/v0.1/vgg.pth
...[net-lin [vgg]] initialized
...Done
Number of images: 3
Images: 100%|██████████████████████████████████████████████████████████████████████████| 3/3 [21:05<00:00, 421.92s/it]
Number of images: 3                                                                                                                                                                                  
Images: 100%|███████████████████████████████████████████████████████████████████████████| 3/3 [04:22<00:00, 87.48s/it]
Loading StyleGAN2 from checkpoint: pretrained_models/ffhq.pt                                                                                                                                         
Align Step 2:   0%|                                                           | 0/100 [00:00<?, ?it/s]
/home/stym/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/functional.py:3103: 
UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, 
and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
Traceback (most recent call last):                                                                                                                                                                   
  File "main.py", line 117, in <module>
    main(args)
  File "main.py", line 43, in main
    align.align_images(im_path1, im_path2, sign=args.sign, align_more_region=False, smooth=args.smooth)
  File "/home/stym/Documents/GitHub/Barbershop/models/Alignment.py", line 305, in align_images
    style_loss = self.loss_builder.style_loss(H1_region, H2_region, mask1=HM_Structure, mask2=HM_G)
  File "/home/stym/Documents/GitHub/Barbershop/losses/align_loss.py", line 33, in style_loss
    loss = self.opt.style_lambda * self.style(im1 * mask1, im2 * mask2, mask1=mask1, mask2=mask2)
  File "/home/stym/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stym/Documents/GitHub/Barbershop/losses/style/style_loss.py", line 111, in forward
    loss = self.cal_style(self.vgg16_act, x, x_hat, mask1=mask1, mask2=mask2)
  File "/home/stym/Documents/GitHub/Barbershop/losses/style/style_loss.py", line 55, in cal_style
    feat_x = self.mask_features(act_x[layer], mask1)
  File "/home/stym/Documents/GitHub/Barbershop/losses/style/style_loss.py", line 28, in mask_features
    mask = prepare_mask(x, mask)
  File "/home/stym/Documents/GitHub/Barbershop/losses/style/custom_loss.py", line 65, in prepare_mask
    mask = F.interpolate(mask, scale_factor=Hx / Hm, mode="nearest")
  File "/home/stym/anaconda3/envs/env1/lib/python3.7/site-packages/torch/nn/functional.py", line 3132, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 3.82 GiB total capacity; 2.13 GiB already allocated; 90.88 MiB free; 2.37 GiB reserved in total by PyTorch)```

**Comment by Styml** [comment]
so seems like all we can do is use better GPU without any workarounds?
