### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by itallmakesense** [ZPdesu/Barbershop#38]
I get this output when running `python align_face.py`:
```
Downloading Shape Predictor
Downloading https://drive.google.com/uc?id=1huhv8PYpNNKbGCLOaYUjOgR1pY5pmbJx ... done
photo_2022-05-01_17-32-49.jpg: Number of faces detected: 1
Traceback (most recent call last):
  File "align_face.py", line 42, in <module>
    face_tensor = torchvision.transforms.ToTensor()(face).unsqueeze(0).cuda()
  File "~/anaconda3/envs/Barbershop/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

Can you please specify in readme, that machine with nvidia card is required for this project to run?

**Comment by petekay** [comment]
I have the same issue. is a nvidia card required, are can we set some gpu flag to False?

**Comment by itallmakesense** [comment]
@petekay I'm afraid such flag would not be possible to do, as majority of the code hardly relies on CUDA (thus, GPU).

**Comment by petekay** [comment]
in the code, there are many `use_gpu` flags, sometimes they are set to `true`. it would make sense to provide a cli option for pure cpu calculation.
