### ISSUE TITLE
RuntimeError: std::bad_alloc

### ISSUE THREAD

**Issue by Jackson-LIMU** [ZPdesu/Barbershop#48]
When i run python align_face.py, error will happen:

911.jpg: Number of faces detected: 1
Traceback (most recent call last):
  File "/data/juicefs_hz_cv_v3/11146533/Barbershop/align_face.py", line 42, in <module>
    face_tensor = torchvision.transforms.ToTensor()(face).unsqueeze(0).cuda()
  File "/root/anaconda3/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 104, in __call__
    return F.to_tensor(pic)
  File "/root/anaconda3/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 96, in to_tensor
    img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
RuntimeError: std::bad_alloc

Anyone help me please!

**Comment by Jackson-LIMU** [comment]
My gpu is Tesla V100 with 32G memory.
